verbose: false
cache_dir: "/opt/rb/var/www/snortrules/cache"
category4_groups:
  - 
    name: "email"
    desc: "email properties"
    regexp: "imap|pop|smtp"
  - 
    name: "web"
    regexp: "^web-|^web_|activex"
  - 
    name: "services"
    regexp: "^dns$|^ftp$|^finger$|netbios|^nntp$|^scada$|^scada_special$|^snmp$|telnet|tftp|^voip$|^x11$|^icmp|^rpc$|rservices"
  - 
    name: "policy"
    regexp: "^chat|^p2p|multimedia|^policy$|content-replace|games|inappropriate"
  - 
    name: "attacks"
    regexp: "attack|backdoor|bad-traffic|botnet-cnc|botcc|exploit|shellcode|spyware-put|specific-threats|virus|scan|^misc$|^info$|phishing|^drop$|spamhaus|malware|trojan|^worm$|^tor$|^rbn$|^rbn-malvertisers$|user_agents|^ciarmy$|compromised|^current_events$|dshield"
  - 
    name: "special"
    regexp: "blacklist|deleted|^local$"
  - 
    name: "sql"
    regexp: "sql|mysql|oracle"
  - 
    name: "dos"
    regexp: "^dos$|^ddos$"

category1_groups:
  - 
    name: "web-activex"
    regexp: "^activex$"
  -
    name: "attack-responses"
    regexp: "^attack-response$"
  -
    name: "botnet-cnc"
    regexp: "^botcc$"
  -
    name: "spamhaus"
    regexp: "^drop$"
  -
    name: "icmp-info"
    regexp: "^icmp_info$"
 


url_rules:
  - 
    name: "etpro" 
    tgzfile: "/opt/rb/var/www/snortrules/cache/etpro.tgz"
    regexp_category3_ignore: "^et |^gpl |^etpro "
    search:
      - "rules"
  - 
    name: "vrt" 
    tgzfile: "/opt/rb/var/www/snortrules/cache/vrt.tar.gz"
    regexp_category3_ignore: "^et |^gpl |^etpro "
    search:
      - "rules"

  #-
  #  name: "emergingthreats" 
  #  domain: "https://rules.emergingthreats.net"
  #  regexp_category1_ignore: "emerging-"
  #  regexp_category3_ignore: "^et |^gpl "
  #  tgz: "https://rules.emergingthreats.net/open/snort-2.9.1/emerging.rules.tar.gz"
  #  md5: "https://rules.emergingthreats.net/open/snort-2.9.1/emerging.rules.tar.gz.md5"
  #  search:
  #    - "rules"
  #-
  #  name: "etpro" 
  #  domain: "https://rules.emergingthreats.net"
  #  regexp_category3_ignore: "^et |^gpl |^etpro "
  #  tgz: "https://rules.emergingthreats.net/<etpro_code>/snort-2.9.1/etpro.rules.tar.gz"
  #  md5: "https://rules.emergingthreats.net/<etpro_code>/snort-2.9.1/etpro.rules.tar.gz.md5"
  #  search:
  #    - "rules"
  #  category3_groups:
  #    - 
  #      name: "facebook"
  #      regexp: "facebook"
  #    - 
  #      name: "mail"
  #      regexp: "imap|pop3"
  #    - 
  #      name: "ibm lotus"
  #      regexp: "ibm lotus"
  #-
  #  name: "vrt" 
  #  domain: "https://www.snort.org"
  #  tgz: "https://www.snort.org/reg-rules/snortrules-snapshot-2900.tar.gz/<snort_oinkcode>"
  #  md5: "https://www.snort.org/reg-rules/snortrules-snapshot-2900.tar.gz.md5/<snort_oinkcode>"
  #  search:
  #    - "rules"
  
