# Oids:
#   Required values:
#     info: Descriptive text for oid
#     text: Showed at the top of graph
#     label: Text for tabs
#
#   Optional values:
#     unit: used for graphs
#     reference: oid for reference. The main oid has to be divided for that value
#     mult: if the value shoud be multiplied by a value
#     inverse: boolean value for that (reference - 'main oid')/reference
#
# time: time frecuency to get values
# level_medium: medium value for severtities
# level_high: high value for serverities
# community: value for snmp servers
#


snorby: &snorby
  oids:
    "1.3.6.1.4.1.2021.11.9.0":
      info: "Percentage of user CPU time"
      text: "User CPU vs Time By Sensor"
      label: "User CPU"
      unit: "%"
    "1.3.6.1.4.1.2021.11.10.0":
      info: "Percentages of system CPU time"
      text: "System CPU vs Time By Sensor"
      label: "Sys CPU"
      unit: "%"
    "1.3.6.1.4.1.2021.4.6.0":
      info: "Percentage RAM used in machine"
      text: "Memory vs Time By Sensor"
      label: "Memory"
      reference: "1.3.6.1.4.1.2021.4.5.0"
      mult: 100
      inverse: true
      unit: "%"
    "1.3.6.1.4.1.2021.9.1.9.1":
      info: "Percentage of space used on disk"
      text: "Disk vs Time By Sensor"
      label: "HDD"
      unit: "%"

  time: '5'
  level_medium: '50'
  level_high: '90'
  community: 'redBorder'


development:
    <<: *snorby

test:
    <<: *snorby
            
production:
    <<: *snorby