production:
  domain: 'rb-manager'
  wkhtmltopdf: /opt/rb/bin/wkhtmltopdf
  mailer_sender: 'rb-manager@redborder.net'
  rules:
    - "/opt/rb/etc/snortrules/rules"
    - "/opt/rb/etc/snortrules/so_rules"
  authentication_mode: ldap

development:
  domain: 'rb-manager'
  wkhtmltopdf: /opt/rb/bin/wkhtmltopdf
  mailer_sender: 'rb-manager@redborder.net'
  rules:
    - "/opt/rb/etc/snortrules/rules"
    - "/opt/rb/etc/snortrules/so_rules"
  authentication_mode: ldap


